# @package _global_
defaults:
  - _self_

provider: vertex

openai_api_key:
model_name: gemini-3.1-flash-lite-preview
max_context_length: 1048576
exllama: False

gcp_project: ${oc.env:GOOGLE_CLOUD_PROJECT}
vertex_model_id: gemini-3.1-flash-lite-preview

system_tag_start: "<|im_start|>system"
system_tag_end: "<|im_end|>"

user_tag_start: "<|im_start|>user"
user_tag_end: "<|im_end|>"

ai_tag_start: "<|im_start|>assistant"
ai_tag_end: "<|im_end|>"

stop_words: